import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import { AuthProvider } from "@/providers/AuthProvider";
=======
>>>>>>> 92459e8 (base set up)
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "LumenPatrons",
  description: "Find non-dilutive capital and institutional backing without the noise.",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 92459e8 (base set up)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 92459e8 (base set up)
    </html>
  );
}
